const ADJECTIVES = [
  "Stormy",
  "Seventh",
  "Opaque",
  "Transparent",
  "Green",
  "Brown",
  "Feral",
  "Scurrilious",
  "Standard",
  "Ancient",
  "Bronze",
  "Broken",
  "Imperial",
  "Tiny",
  "Big",
  "Smelly",
  "Pristine",
  "Girthy",
  "Expensive",
  "Excruciating",
  "Lovesick",
  "Vulgar",
  "Angelic",
  "Chaotic",
  "Interdimensional",
];

const NOUNS = [
  "Dog",
  "Diaper",
  "Musketeer",
  "Princess",
  "Mermaid",
  "Man",
  "Table",
  "Mathematics",
  "Elder",
  "Microbe",
  "Santa",
  "Lexer",
  "Parser",
  "Undertaker",
  "Pink",
  "Gray",
  "Blade",
  "Chocolate",
  "Herbs",
  "Boquets",
  "CPR_Training",
  "Payload",
  "Tower",
  "Psychiatry",
  "Chaos",
  "Spillover",
  "Growth",
  "Hacking",
  "Rubix_Cube",
  "Cupid",
];

export const generateRandomUserName = () => {
  const adjective = ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)];
  const noun = NOUNS[Math.floor(Math.random() * NOUNS.length)];
  return `${adjective}_${noun}`;
};
