# Publishes storybook on Chromatic on push
name: "Publish Storybook on Chromatic"

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Publish storybook to chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
